version: "3"

services:
  app:
    image: app
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DB_TYPE: sqlite
      DB_FILE: /path/to/sqlite3/database.db  # Change the path to your SQLite database file
